import React, { useState } from 'react';
import { useOMA } from '../context/OMAContext';
import { useOperations } from '../context/OperationsContext';
import { useData } from '../context/DataContext';
import { useAuth } from '../context/AuthContext';
import { WorkOrder } from '../types';
import './Pages.css';

const OMA: React.FC = () => {
  const { user } = useAuth();
  const { workOrders, addWorkOrder, updateWorkOrder } = useOMA();
  const { aircraft } = useOperations();
  const { parts } = useData();

  const [filterStatus, setFilterStatus] = useState('');
  const [filterAircraft, setFilterAircraft] = useState('');
  const [showForm, setShowForm] = useState(false);

  const [form, setForm] = useState({
    aircraftId: '', taskCode: '', description: '',
    type: 'scheduled' as WorkOrder['type'],
    priority: 'medium' as WorkOrder['priority'],
    projectedDate: '', assignedTo: '', notes: '',
  });

  // Verificar disponibilidad de piezas en almacén
  const checkPartsAvailability = (wo: WorkOrder): boolean => {
    if (wo.partsRequired.length === 0) return true;
    return wo.partsRequired.every(req => {
      const part = parts.find(p => p.items.some(i => i.partNumber === req.partNumber));
      if (!part) return false;
      const available = part.items.filter(i => i.status === 'available').length;
      return available >= req.quantityRequired;
    });
  };

  const submitWO = (e: React.FormEvent) => {
    e.preventDefault();
    const ac = aircraft.find(a => a.id === form.aircraftId);
    if (!ac) return;
    addWorkOrder({
      aircraftId: ac.id,
      aircraftRegistration: ac.registration,
      taskCode: form.taskCode,
      description: form.description,
      type: form.type,
      priority: form.priority,
      projectedDate: form.projectedDate,
      status: 'pending',
      assignedTo: form.assignedTo,
      partsRequired: [],
      partsAvailable: true,
      createdBy: user?.username || '',
      notes: form.notes,
      autoGenerated: false,
    });
    setForm({ aircraftId: '', taskCode: '', description: '', type: 'scheduled', priority: 'medium', projectedDate: '', assignedTo: '', notes: '' });
    setShowForm(false);
  };

  const filtered = workOrders.filter(w =>
    (!filterStatus || w.status === filterStatus) &&
    (!filterAircraft || w.aircraftId === filterAircraft)
  );

  const priorityLabel = (p: WorkOrder['priority']) => {
    const map = { low: 'Baja', medium: 'Media', high: 'Alta', critical: 'Crítica' };
    const cls = { low: 'priority-low', medium: 'priority-medium', high: 'priority-high', critical: 'priority-urgent' };
    return <span className={`priority ${cls[p]}`}>{map[p]}</span>;
  };

  const statusLabel = (s: WorkOrder['status']) => {
    const map = { pending: 'Pendiente', in_progress: 'En Progreso', completed: 'Completada', cancelled: 'Cancelada' };
    const cls = { pending: 'status-pending', in_progress: 'status-reserved', completed: 'status-approved', cancelled: 'status-rejected' };
    return <span className={`status ${cls[s]}`}>{map[s]}</span>;
  };

  const pendingAlerts = workOrders.filter(w => w.autoGenerated && w.status === 'pending');

  return (
    <div className="page-container">
      <div className="page-header">
        <h2>📋 OMA — Órdenes de Trabajo</h2>
        <button className="btn-primary" onClick={() => setShowForm(!showForm)}>
          {showForm ? 'Cancelar' : '+ Nueva OT'}
        </button>
      </div>

      {/* Alertas de OTs automáticas */}
      {pendingAlerts.length > 0 && (
        <div style={{ background: '#f8d7da', border: '1px solid #e74c3c', borderRadius: 8, padding: 16, marginBottom: 20 }}>
          <strong>🔴 {pendingAlerts.length} OT(s) generadas automáticamente por Ingeniería pendientes de atención:</strong>
          <ul style={{ margin: '8px 0 0 20px' }}>
            {pendingAlerts.map(w => (
              <li key={w.id} style={{ color: '#721c24', marginBottom: 4 }}>
                <strong>{w.workOrderNumber}</strong> — {w.aircraftRegistration} — {w.description}
                {' '}(Proyectada: {w.projectedDate})
              </li>
            ))}
          </ul>
        </div>
      )}

      {showForm && (
        <form className="form-card" onSubmit={submitWO}>
          <h3>Nueva Orden de Trabajo</h3>
          <div className="form-grid">
            <select value={form.aircraftId} onChange={e => setForm(p => ({ ...p, aircraftId: e.target.value }))} required>
              <option value="">Seleccionar aeronave</option>
              {aircraft.map(a => <option key={a.id} value={a.id}>{a.registration} - {a.model}</option>)}
            </select>
            <input placeholder="Código de tarea" value={form.taskCode} onChange={e => setForm(p => ({ ...p, taskCode: e.target.value }))} required />
            <select value={form.type} onChange={e => setForm(p => ({ ...p, type: e.target.value as WorkOrder['type'] }))}>
              <option value="scheduled">Programado</option>
              <option value="unscheduled">No programado</option>
              <option value="inspection">Inspección</option>
            </select>
            <select value={form.priority} onChange={e => setForm(p => ({ ...p, priority: e.target.value as WorkOrder['priority'] }))}>
              <option value="low">Baja</option>
              <option value="medium">Media</option>
              <option value="high">Alta</option>
              <option value="critical">Crítica</option>
            </select>
            <input type="date" placeholder="Fecha proyectada" value={form.projectedDate} onChange={e => setForm(p => ({ ...p, projectedDate: e.target.value }))} required />
            <input placeholder="Asignado a" value={form.assignedTo} onChange={e => setForm(p => ({ ...p, assignedTo: e.target.value }))} />
          </div>
          <input placeholder="Descripción del trabajo" value={form.description} onChange={e => setForm(p => ({ ...p, description: e.target.value }))} required style={{ width: '100%', padding: 10, border: '1px solid #ddd', borderRadius: 5, margin: '10px 0' }} />
          <input placeholder="Notas adicionales" value={form.notes} onChange={e => setForm(p => ({ ...p, notes: e.target.value }))} style={{ width: '100%', padding: 10, border: '1px solid #ddd', borderRadius: 5 }} />
          <div className="form-actions" style={{ marginTop: 15 }}>
            <button type="submit" className="btn-primary">Crear OT</button>
          </div>
        </form>
      )}

      {/* Filtros */}
      <div className="form-grid" style={{ marginBottom: 20 }}>
        <select value={filterAircraft} onChange={e => setFilterAircraft(e.target.value)}>
          <option value="">Todas las aeronaves</option>
          {aircraft.map(a => <option key={a.id} value={a.id}>{a.registration}</option>)}
        </select>
        <select value={filterStatus} onChange={e => setFilterStatus(e.target.value)}>
          <option value="">Todos los estados</option>
          <option value="pending">Pendiente</option>
          <option value="in_progress">En Progreso</option>
          <option value="completed">Completada</option>
          <option value="cancelled">Cancelada</option>
        </select>
      </div>

      {/* Resumen */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 15, marginBottom: 25 }}>
        {(['pending', 'in_progress', 'completed', 'cancelled'] as WorkOrder['status'][]).map(s => {
          const count = workOrders.filter(w => w.status === s).length;
          const colors = { pending: '#fff3cd', in_progress: '#cce5ff', completed: '#d4edda', cancelled: '#f8d7da' };
          const labels = { pending: 'Pendientes', in_progress: 'En Progreso', completed: 'Completadas', cancelled: 'Canceladas' };
          return (
            <div key={s} style={{ background: colors[s], borderRadius: 8, padding: 16, textAlign: 'center' }}>
              <div style={{ fontSize: 28, fontWeight: 'bold' }}>{count}</div>
              <div style={{ fontSize: 13, color: '#555' }}>{labels[s]}</div>
            </div>
          );
        })}
      </div>

      {filtered.length === 0 ? (
        <div className="empty-state">No hay órdenes de trabajo.</div>
      ) : (
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>N° OT</th><th>Aeronave</th><th>Código</th><th>Descripción</th>
                <th>Tipo</th><th>Prioridad</th><th>Fecha Proyectada</th>
                <th>Almacén</th><th>Estado</th><th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              {filtered.map(w => {
                const partsOk = checkPartsAvailability(w);
                return (
                  <tr key={w.id} style={{ background: w.autoGenerated ? '#fffbf0' : undefined }}>
                    <td>
                      <strong>{w.workOrderNumber}</strong>
                      {w.autoGenerated && <span style={{ fontSize: 10, background: '#f39c12', color: 'white', borderRadius: 3, padding: '1px 5px', marginLeft: 5 }}>AUTO</span>}
                    </td>
                    <td>{w.aircraftRegistration}</td>
                    <td>{w.taskCode}</td>
                    <td>{w.description}</td>
                    <td>{w.type === 'scheduled' ? 'Programado' : w.type === 'unscheduled' ? 'No programado' : 'Inspección'}</td>
                    <td>{priorityLabel(w.priority)}</td>
                    <td>{w.projectedDate}</td>
                    <td>
                      {w.partsRequired.length === 0
                        ? <span className="status status-approved">N/A</span>
                        : partsOk
                          ? <span className="status status-approved">✅ Disponible</span>
                          : <span className="status status-rejected">❌ Sin stock</span>
                      }
                    </td>
                    <td>{statusLabel(w.status)}</td>
                    <td>
                      <div className="action-buttons">
                        {w.status === 'pending' && (
                          <button className="btn-small" style={{ background: '#3498db' }} onClick={() => updateWorkOrder(w.id, { status: 'in_progress' })}>
                            Iniciar
                          </button>
                        )}
                        {w.status === 'in_progress' && (
                          <button className="btn-approve" onClick={() => updateWorkOrder(w.id, { status: 'completed', completedDate: new Date().toISOString() })}>
                            Completar
                          </button>
                        )}
                        {(w.status === 'pending' || w.status === 'in_progress') && (
                          <button className="btn-small" onClick={() => updateWorkOrder(w.id, { status: 'cancelled' })}>
                            Cancelar
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default OMA;
