import React, { createContext, useContext, useState, ReactNode } from 'react';
import { WorkOrder } from '../types';

interface OMAContextType {
  workOrders: WorkOrder[];
  addWorkOrder: (wo: Omit<WorkOrder, 'id' | 'workOrderNumber' | 'createdDate'>) => void;
  updateWorkOrder: (id: string, updates: Partial<WorkOrder>) => void;
  deleteWorkOrder: (id: string) => void;
  generateFromComponent: (params: {
    componentId: string;
    aircraftId: string;
    aircraftRegistration: string;
    description: string;
    taskCode: string;
    projectedDate: string;
    createdBy: string;
  }) => void;
}

const OMAContext = createContext<OMAContextType | undefined>(undefined);

function genWONumber(count: number) {
  const d = new Date();
  return `OT-${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}-${String(count + 1).padStart(4, '0')}`;
}

export const OMAProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [workOrders, setWorkOrders] = useState<WorkOrder[]>([]);

  const addWorkOrder = (wo: Omit<WorkOrder, 'id' | 'workOrderNumber' | 'createdDate'>) => {
    setWorkOrders(prev => {
      const newWO: WorkOrder = {
        ...wo,
        id: Date.now().toString(),
        workOrderNumber: genWONumber(prev.length),
        createdDate: new Date().toISOString(),
      };
      return [newWO, ...prev];
    });
  };

  const updateWorkOrder = (id: string, updates: Partial<WorkOrder>) =>
    setWorkOrders(prev => prev.map(w => w.id === id ? { ...w, ...updates } : w));

  const deleteWorkOrder = (id: string) =>
    setWorkOrders(prev => prev.filter(w => w.id !== id));

  const generateFromComponent = (params: {
    componentId: string;
    aircraftId: string;
    aircraftRegistration: string;
    description: string;
    taskCode: string;
    projectedDate: string;
    createdBy: string;
  }) => {
    setWorkOrders(prev => {
      const newWO: WorkOrder = {
        id: Date.now().toString(),
        workOrderNumber: genWONumber(prev.length),
        componentId: params.componentId,
        aircraftId: params.aircraftId,
        aircraftRegistration: params.aircraftRegistration,
        taskCode: params.taskCode,
        description: params.description,
        type: 'scheduled',
        priority: 'high',
        projectedDate: params.projectedDate,
        status: 'pending',
        partsRequired: [],
        partsAvailable: false,
        createdBy: params.createdBy,
        createdDate: new Date().toISOString(),
        autoGenerated: true,
      };
      return [newWO, ...prev];
    });
  };

  return (
    <OMAContext.Provider value={{ workOrders, addWorkOrder, updateWorkOrder, deleteWorkOrder, generateFromComponent }}>
      {children}
    </OMAContext.Provider>
  );
};

export const useOMA = () => {
  const ctx = useContext(OMAContext);
  if (!ctx) throw new Error('useOMA must be used within OMAProvider');
  return ctx;
};
