import React, { createContext, useContext, useState, ReactNode } from 'react';
import { WorkOrder } from '../types';

interface OMAContextType {
  workOrders: WorkOrder[];
  addWorkOrder: (wo: Omit<WorkOrder, 'id' | 'workOrderNumber' | 'createdDate'>) => void;
  updateWorkOrder: (id: string, updates: Partial<WorkOrder>) => void;
  deleteWorkOrder: (id: string) => void;
  generateFromComponent: (params: { componentId: string; aircraftId: string; aircraftRegistration: string; description: string; taskCode: string; projectedDate: string; createdBy: string; }) => void;
}

const OMAContext = createContext<OMAContextType | undefined>(undefined);

function genWONumber(count: number) {
  const d = new Date();
  return `OT-${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}-${String(count + 1).padStart(4, '0')}`;
}

const sampleWorkOrders: WorkOrder[] = [
  { id: 'wo1', workOrderNumber: 'OT-202405-0001', aircraftId: '1', aircraftRegistration: 'HK-1234', taskCode: 'TASK-100H', description: 'Inspección 100 horas motor PT6A-114A', type: 'scheduled', priority: 'medium', projectedDate: '2024-05-15', status: 'completed', completedDate: '2024-05-14T10:00:00Z', assignedTo: 'almacen', partsRequired: [{ partNumber: 'PN-FO-PT6-01', description: 'Filtro de aceite', quantityRequired: 1, quantityAvailable: 5 }], partsAvailable: true, createdBy: 'admin', createdDate: '2024-05-01T08:00:00Z', autoGenerated: false },
  { id: 'wo2', workOrderNumber: 'OT-202405-0002', aircraftId: '2', aircraftRegistration: 'HK-5678', taskCode: 'TASK-TY-REPL', description: 'Reemplazo neumáticos tren principal', type: 'scheduled', priority: 'high', projectedDate: '2024-05-20', status: 'in_progress', assignedTo: 'almacen', partsRequired: [{ partNumber: 'PN-TY-850-01', description: 'Neumático 8.50-10', quantityRequired: 2, quantityAvailable: 3 }], partsAvailable: true, createdBy: 'admin', createdDate: '2024-05-05T09:00:00Z', autoGenerated: true },
  { id: 'wo3', workOrderNumber: 'OT-202405-0003', aircraftId: '1', aircraftRegistration: 'HK-1234', taskCode: 'TASK-FO-REPL', description: 'Reemplazo filtro de aceite — alerta remanente', type: 'scheduled', priority: 'high', projectedDate: '2024-05-25', status: 'pending', assignedTo: 'almacen', partsRequired: [{ partNumber: 'PN-FO-PT6-01', description: 'Filtro de aceite PT6', quantityRequired: 1, quantityAvailable: 5 }], partsAvailable: true, createdBy: 'sistema', createdDate: '2024-05-10T07:00:00Z', autoGenerated: true },
  { id: 'wo4', workOrderNumber: 'OT-202405-0004', aircraftId: '2', aircraftRegistration: 'HK-5678', taskCode: 'TASK-BAT-REPL', description: 'Reemplazo batería de arranque 24V — VENCIDA', type: 'unscheduled', priority: 'critical', projectedDate: '2024-05-12', status: 'pending', partsRequired: [{ partNumber: 'PN-BAT-24V-01', description: 'Batería 24V', quantityRequired: 1, quantityAvailable: 1 }], partsAvailable: true, createdBy: 'sistema', createdDate: '2024-05-11T06:00:00Z', autoGenerated: true },
  { id: 'wo5', workOrderNumber: 'OT-202404-0001', aircraftId: '3', aircraftRegistration: 'HK-9012', taskCode: 'TASK-INSP-50H', description: 'Inspección general 50 horas', type: 'inspection', priority: 'low', projectedDate: '2024-04-30', status: 'completed', completedDate: '2024-04-29T14:00:00Z', assignedTo: 'almacen', partsRequired: [], partsAvailable: true, createdBy: 'admin', createdDate: '2024-04-20T08:00:00Z', autoGenerated: false },
  { id: 'wo6', workOrderNumber: 'OT-202405-0005', aircraftId: '1', aircraftRegistration: 'HK-1234', taskCode: 'TASK-SP-REPL', description: 'Reemplazo bujías de encendido', type: 'scheduled', priority: 'medium', projectedDate: '2024-06-01', status: 'pending', partsRequired: [{ partNumber: 'PN-SP-CH-01', description: 'Bujías Champion', quantityRequired: 4, quantityAvailable: 3 }], partsAvailable: false, createdBy: 'admin', createdDate: '2024-05-12T10:00:00Z', autoGenerated: false },
];

export const OMAProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [workOrders, setWorkOrders] = useState<WorkOrder[]>(sampleWorkOrders);

  const addWorkOrder = (wo: Omit<WorkOrder, 'id' | 'workOrderNumber' | 'createdDate'>) => {
    setWorkOrders(prev => {
      const newWO: WorkOrder = { ...wo, id: Date.now().toString(), workOrderNumber: genWONumber(prev.length), createdDate: new Date().toISOString() };
      return [newWO, ...prev];
    });
  };

  const updateWorkOrder = (id: string, updates: Partial<WorkOrder>) =>
    setWorkOrders(prev => prev.map(w => w.id === id ? { ...w, ...updates } : w));

  const deleteWorkOrder = (id: string) =>
    setWorkOrders(prev => prev.filter(w => w.id !== id));

  const generateFromComponent = (params: { componentId: string; aircraftId: string; aircraftRegistration: string; description: string; taskCode: string; projectedDate: string; createdBy: string; }) => {
    setWorkOrders(prev => {
      const newWO: WorkOrder = { id: Date.now().toString(), workOrderNumber: genWONumber(prev.length), componentId: params.componentId, aircraftId: params.aircraftId, aircraftRegistration: params.aircraftRegistration, taskCode: params.taskCode, description: params.description, type: 'scheduled', priority: 'high', projectedDate: params.projectedDate, status: 'pending', partsRequired: [], partsAvailable: false, createdBy: params.createdBy, createdDate: new Date().toISOString(), autoGenerated: true };
      return [newWO, ...prev];
    });
  };

  return (
    <OMAContext.Provider value={{ workOrders, addWorkOrder, updateWorkOrder, deleteWorkOrder, generateFromComponent }}>
      {children}
    </OMAContext.Provider>
  );
};

export const useOMA = () => {
  const ctx = useContext(OMAContext);
  if (!ctx) throw new Error('useOMA must be used within OMAProvider');
  return ctx;
};
